name: spoon_the_restaurant
description: A new Flutter project.


publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  google_fonts:
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
##    - assets/azkar/
    - assets/images/
##    - assets/translations/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

